title: Tamela Maciel # your name (or website title) here
logo: "/images/thumbnail.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD astrophysicist. Data Scientist.
  <br>
  Space Communications Manager. 
  <br>
  Physics editor. Science writer.
  <br><br>
  <a href="https://www.linkedin.com/in/tamelamaciel/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://twitter.com/TamelaMaciel">Find Me On Twitter</a>
theme: jekyll-theme-minimal
google_analytics: UA-167444377-1 # your Google Analytics tracking ID here
